language: node_js
node_js:
  - node
cache: yarn
branches:
  only: master
before_install:
  - yarn global add firebase-tools
  - yarn
install:
  - yarn test
  - yarn build
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN} --project=${FIREBASE_PROJECT}
